### ISSUE TITLE
Support for IMDSv2

### ISSUE THREAD

**Issue by jakeyheath** [chanzuckerberg/swipe#13]
### Description
It would be great if Swipe supported IMDSv2. Right now, prodsec and infrasec are trying to enable this feature to help defend against Server-Side Request Forgery (SSRF) attacks, but it requires the caller to the metadata endpoint first make a PUT request to grab a short-lived token and then make a GET request to the metadata endpoint with that token in the header.

### References
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html
https://czi.atlassian.net/wiki/spaces/INFRASEC/pages/2090696711/AWS+Metadata+V2+Migration
https://github.com/chanzuckerberg/SSRFs-Up
https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/
https://github.com/chanzuckerberg/SSRFs-Up/wiki/FAQ#i-read-the-other-docs-but-i-still-dont-really-get-why-this-matters-can-you-provide-an-example-of-how-ssrf-affects-my-application

### Proposed Change

~~~
% git diff origin/main
diff --git a/terraform/modules/swipe-sfn-batch-job/batch_job_container_properties.yml b/terraform/modules/swipe-sfn-batch-job/batch_job_container_properties.yml
index 095cd9e..5f174a8 100644
--- a/terraform/modules/swipe-sfn-batch-job/batch_job_container_properties.yml
+++ b/terraform/modules/swipe-sfn-batch-job/batch_job_container_properties.yml
@@ -11,7 +11,7 @@ image: "${batch_docker_image}"
 command:
   - "/bin/bash"
   - "-c"
-  - "for i in \"$@\"; do eval \"$i\"; done; cd /"
+  - 'for i in "$@"; do eval "$i"; done; cd /'
   - "swipe"
   - "set -a"
   - "if [ -f /etc/environment ]; then source /etc/environment; fi"
@@ -19,7 +19,7 @@ command:
   - "set +a"
   - >-
     while true; do
-    if curl -sf http://169.254.169.254/latest/meta-data/spot/instance-action; then
+    if TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" && curl -H "X-aws-ec2-metadata-token: $TOKEN" -sf http://169.254.169.254/latest/meta-data/spot/instance-action; then
     echo WARNING: THIS SPOT INSTANCE HAS BEEN SCHEDULED FOR TERMINATION >> /dev/stderr;
     fi;
     sleep 10;
~~~

**Comment by morsecodist** [comment]
@jakeyheath this has been completed, sorry for closing this so late https://github.com/chanzuckerberg/swipe/blob/main/scripts/init.sh#L17
